Histogram-Based Gradient Boosting Model

Excerpt on Model Background (source: https://scikit-learn.org/stable/modules/ensemble.html#histogram-based-gradient-boosting):

"Scikit-learn 0.21 introduced two new implementations of gradient boosting trees, namely HistGradientBoostingClassifier and HistGradientBoostingRegressor, inspired by LightGBM (See [LightGBM]).

These histogram-based estimators can be orders of magnitude faster than GradientBoostingClassifier and GradientBoostingRegressor when the number of samples is larger than tens of thousands of samples."

In [3]:
#import dependencies
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import classification_report

In [4]:
#read and view data
df = pd.read_csv("../cleaned_data_final.csv")

# Review the DataFrame
df

,cnt_mrtg_term,mrtg_status,rate_ltv,cd_fxfltr,cnt_blln_term,cnt_io_per,cnt_rsdntl_unit,code_int,rate_dcr,rate_int
0,87,500,0.79122,1,1,0,336.0,0.0,1.311000,0.059400
1,300,500,0.77500,0,0,0,216.0,0.0,1.310000,0.070000
2,84,500,0.69504,0,1,1,120.0,0.0,1.785000,0.043500
3,180,500,0.80000,0,1,0,60.0,0.0,1.354000,0.077500
4,120,100,0.77500,0,1,1,328.0,0.0,1.689556,0.043700
...,...,...,...,...,...,...,...,...,...,...
54646,132,500,0.72741,1,1,1,128.0,0.0,1.765000,0.055500
54647,84,500,0.74153,0,1,0,346.0,0.0,1.251000,0.041400
54648,120,100,0.63505,0,1,1,191.0,0.0,1.708517,0.042700
54649,84,500,0.80000,0,1,1,328.0,1.0,1.959734,0.038969
54650,120,100,0.67453,0,1,1,26.0,0.0,1.593434,0.054800